/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import trandpl.dao.HrDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.HrPojo;

/**
 *
 * @author aadarsh jain
 */
public class AdminAddNewHrFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddNewHrFrame
     */
    private String password;
    private String confrmpwd;
    public AdminAddNewHrFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());
        loadId();
    }
    
    private void loadId(){
        try{
            int hrId=HrDAO.getNewHrId();
            lblHrId.setText("Hr-"+hrId);
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "DB Error ","Error in generating HrID",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private boolean validateInputs(){
        password=String.valueOf(txtPwd.getPassword());
        confrmpwd=String.valueOf(txtCnfrmPwd.getPassword());
        int index=jcProff.getSelectedIndex();
        if(txtName.getText().isEmpty()||txtMail.getText().isEmpty()||txtMob.getText().isEmpty()||txtCompany.getText().isEmpty()||password.isEmpty()||confrmpwd.isEmpty() || index==0)
             return false;
        return true;
    }
     
    private boolean matchPasswords(){
        return password.equals(confrmpwd);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHrId = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtMob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jcProff = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCnfrmPwd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAddNewHr = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel.setBackground(new java.awt.Color(243, 246, 254));
        myPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        myPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 200));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Welcome ,");
        myPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        myPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 187, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Hr id :-");
        myPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Company name");
        myPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, 30));

        lblHrId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        myPanel.add(lblHrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 226, 30));

        txtCompany.setBackground(new java.awt.Color(243, 246, 254));
        txtCompany.setBorder(null);
        myPanel.add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 183, 30));
        myPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 254, 240, -1));
        myPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 256, 210, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Name");
        myPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));
        myPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 266, 710, -1));

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtName.setBorder(null);
        myPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 290, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        myPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 340, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        myPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMail.setBorder(null);
        myPanel.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 300, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        myPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 340, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Moblie no");
        myPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, 20));

        btnBack.setBackground(new java.awt.Color(173, 192, 234));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        myPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        txtMob.setBackground(new java.awt.Color(173, 192, 234));
        txtMob.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMob.setBorder(null);
        myPanel.add(txtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 300, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        myPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 340, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Profession in");
        myPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 80, 20));

        txtPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtPwd.setBorder(null);
        myPanel.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 310, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        myPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 340, 40));

        jcProff.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jcProff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Profession", "Developer", "Aptitude", "Technical", "Digital Marketing" }));
        myPanel.add(jcProff, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 330, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Password");
        myPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Confirm Password");
        myPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, 20));

        txtCnfrmPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtCnfrmPwd.setBorder(null);
        myPanel.add(txtCnfrmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 310, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        myPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNewEmp.png"))); // NOI18N
        myPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 190));

        btnAddNewHr.setBackground(new java.awt.Color(173, 192, 234));
        btnAddNewHr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddNewHr.setText("Add New HR");
        btnAddNewHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewHrActionPerformed(evt);
            }
        });
        myPanel.add(btnAddNewHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        btnLogout.setBackground(new java.awt.Color(173, 192, 234));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        myPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewHrActionPerformed
        // TODO add your handling code here:
        final String username="aadarshjain8269@gmail.com";
        final String Pwd="fvooieqpgebxcpvw";
        //step 1
        Properties prop = new Properties();
	prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        
        MyAuthenticator myAuth=new  MyAuthenticator(username,Pwd);
        Session session=Session.getInstance(prop, myAuth);
        
        if(validateInputs()==false){
            JOptionPane.showMessageDialog(null, "Please input all the fields ","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(matchPasswords()==false){
            JOptionPane.showMessageDialog(null, "Password do not match ","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
         HrPojo hr=new HrPojo();
            hr.setUserId(txtMail.getText().trim().toUpperCase());
            hr.setHrId(lblHrId.getText().trim());
            hr.setHrName(txtName.getText().trim());
            hr.setCompanyName(txtCompany.getText().trim());
            hr.setPassword(password);
            hr.setProfession(jcProff.getSelectedItem().toString());
            hr.setPhone(txtMob.getText().trim());
            hr.setType("Hr");
        try{
           
            int result=HrDAO.addNewHr(hr);
            if(result==1){
                JOptionPane.showMessageDialog(null, "Record Added! ","Success!",JOptionPane.INFORMATION_MESSAGE);
                 Message message=new MimeMessage(session);
            InternetAddress[]recipients=InternetAddress.parse(hr.getUserId());
            
            message.setRecipients(Message.RecipientType.TO, recipients);
            message.setSubject(CurrentUser.getName());
            message.setText("You are added into TNP Application and your UserId is "+hr.getUserId()+" and Password is "+hr.getPassword());
            Transport.send(message);
            System.out.println("Mail successfully send");
                 clearAll();
                 loadId();
                return;
            }else if(result==-1){
                JOptionPane.showMessageDialog(null, "This Email Id Is Already Registered ","Error!",JOptionPane.ERROR_MESSAGE);
            return;
            }else{
                JOptionPane.showMessageDialog(null, "Cannot add the record ","Error",JOptionPane.ERROR_MESSAGE);
            return;
            }
             
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "DB Error ","Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        catch (MessagingException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddNewHrActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed
     private void clearAll(){
         txtName.setText("");
         txtMail.setText("");
         txtCompany.setText("");
         txtMob.setText("");
         txtPwd.setText("");
         txtCnfrmPwd.setText("");
        jcProff.setSelectedIndex(0);
         
     }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminHrModuleFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddNewHrFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewHr;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcProff;
    private javax.swing.JLabel lblHrId;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPasswordField txtCnfrmPwd;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMob;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables
}
