/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;



import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trandpl.dao.HrDAO;
import trandpl.dao.ParticipantsDAO;
import trandpl.dao.ResultDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.ParticipantJobPojo;
import trandpl.pojo.ParticipantsPojo;
import trandpl.pojo.ResultsPojo;

/**
 *
 * @author aadarsh jain
 */
class MyAuthenticator extends Authenticator{
    private String username,password;
    public MyAuthenticator(String username,String password){
        this.username=username;
        this.password=password;
    }
    @Override
     protected PasswordAuthentication getPasswordAuthentication() {
       PasswordAuthentication pwdAuth=new PasswordAuthentication(username,password);
       return pwdAuth;
    }
}
public class HrViewParticipantFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrViewParticipantFrame
     */
   
    private ParticipantsPojo participant;
    public String participantid;
    public HrViewParticipantFrame(String Pid) {
        initComponents();
        this.setLocationRelativeTo(null);
       
        participantid=Pid;
        loadParticipantDetails();
       
    }

    public void loadParticipantDetails(){
        try{
            participant=ParticipantsDAO.getParticipantDetails(participantid);
            lblParticipantid.setText(participant.getId());
            txtName.setText(participant.getName());
            txtPhone.setText(participant.getPhone());
            txtMail2.setText(participant.getUserId());
            txtQualification2.setText(participant.getQualifications());
            String tags[]=participant.getSkills().split(",");
            txtSkill9.setText(tags[0]);
            txtSkill10.setText(tags[1]);
            txtSkill11.setText(tags[2]);
            txtSkill12.setText(tags[3]);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB Error ","Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnBrowseFile = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        txtSkill1 = new javax.swing.JTextField();
        txtSkill2 = new javax.swing.JTextField();
        txtSkill3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSkill4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        txtPwd = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        txtCnfPwd = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblPid1 = new javax.swing.JLabel();
        txtQualification1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPhone2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtMail1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnBrowseFile1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        txtFilePath1 = new javax.swing.JTextField();
        txtSkill5 = new javax.swing.JTextField();
        txtSkill6 = new javax.swing.JTextField();
        txtSkill7 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtSkill8 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        btnCreateAccount1 = new javax.swing.JButton();
        txtPwd1 = new javax.swing.JPasswordField();
        jLabel38 = new javax.swing.JLabel();
        txtCnfPwd1 = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblParticipantid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMail2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        txtSkill9 = new javax.swing.JTextField();
        txtSkill10 = new javax.swing.JTextField();
        txtSkill11 = new javax.swing.JTextField();
        txtSkill12 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtQualification2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        btnDownloadResume = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        btnSendMail = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(243, 246, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 170));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel8.setText("Participants id :-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        lblPid.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jPanel2.add(lblPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 71, 20));

        txtQualification.setBackground(new java.awt.Color(173, 192, 234));
        txtQualification.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtQualification.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 760, 30));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel9.setText("Email :-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 110, -1));

        txtPhone1.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtPhone1.setBorder(null);
        jPanel2.add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 300, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtName1.setBackground(new java.awt.Color(173, 192, 234));
        txtName1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtName1.setBorder(null);
        jPanel2.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 300, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtMail.setBorder(null);
        jPanel2.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 300, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel10.setText("Name :-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 538, 950, -1));

        jLabel17.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel17.setText("Mobile no :-");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, -1));

        jLabel18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel18.setText("Upload Resume");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, -1));

        btnBrowseFile.setBackground(new java.awt.Color(173, 192, 234));
        btnBrowseFile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBrowseFile.setText("Browse File");
        btnBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFileActionPerformed(evt);
            }
        });
        jPanel2.add(btnBrowseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 100, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 10));

        jLabel19.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel19.setText("Skills -");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, -1));

        txtFilePath.setBackground(new java.awt.Color(173, 192, 234));
        txtFilePath.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtFilePath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 230, 30));

        txtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 30));

        txtSkill2.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 160, 30));

        txtSkill3.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 160, 30));

        jLabel20.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel20.setText("Qualification :-");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 170, -1));

        txtSkill4.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtSkill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 160, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 950, 10));

        jLabel21.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel21.setText("Password :-");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, -1));

        jLabel22.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel22.setText("Confirm Password :-");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 130, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 950, -1));

        jButton2.setBackground(new java.awt.Color(173, 192, 234));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Login Page");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        btnCreateAccount.setBackground(new java.awt.Color(173, 192, 234));
        btnCreateAccount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        txtPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtPwd.setBorder(null);
        jPanel2.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 310, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 340, 40));

        txtCnfPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtCnfPwd.setBorder(null);
        jPanel2.add(txtCnfPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 310, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        jPanel3.setBackground(new java.awt.Color(243, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 170));

        jLabel26.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel26.setText("Participants id :-");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        lblPid1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jPanel3.add(lblPid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 71, 20));

        txtQualification1.setBackground(new java.awt.Color(173, 192, 234));
        txtQualification1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtQualification1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtQualification1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 760, 30));

        jLabel27.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel27.setText("Email :-");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 110, -1));

        txtPhone2.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtPhone2.setBorder(null);
        jPanel3.add(txtPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 300, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtName2.setBackground(new java.awt.Color(173, 192, 234));
        txtName2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtName2.setBorder(null);
        jPanel3.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 300, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtMail1.setBackground(new java.awt.Color(173, 192, 234));
        txtMail1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtMail1.setBorder(null);
        jPanel3.add(txtMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 300, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel31.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel31.setText("Name :-");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 538, 950, -1));

        jLabel32.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel32.setText("Mobile no :-");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, -1));

        jLabel33.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel33.setText("Upload Resume");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, -1));

        btnBrowseFile1.setBackground(new java.awt.Color(173, 192, 234));
        btnBrowseFile1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBrowseFile1.setText("Browse File");
        btnBrowseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFile1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBrowseFile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 100, 30));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 10));

        jLabel34.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel34.setText("Skills -");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, -1));

        txtFilePath1.setBackground(new java.awt.Color(173, 192, 234));
        txtFilePath1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtFilePath1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtFilePath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 230, 30));

        txtSkill5.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSkill5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 30));

        txtSkill6.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSkill6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 160, 30));

        txtSkill7.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSkill7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 160, 30));

        jLabel35.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel35.setText("Qualification :-");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 170, -1));

        txtSkill8.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSkill8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 160, 30));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 950, 10));

        jLabel36.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel36.setText("Password :-");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, -1));

        jLabel37.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel37.setText("Confirm Password :-");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 130, -1));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 950, -1));

        jButton3.setBackground(new java.awt.Color(173, 192, 234));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Login Page");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        btnCreateAccount1.setBackground(new java.awt.Color(173, 192, 234));
        btnCreateAccount1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateAccount1.setText("Create Account");
        btnCreateAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccount1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCreateAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        txtPwd1.setBackground(new java.awt.Color(173, 192, 234));
        txtPwd1.setBorder(null);
        jPanel3.add(txtPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 310, 20));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 340, 40));

        txtCnfPwd1.setBackground(new java.awt.Color(173, 192, 234));
        txtCnfPwd1.setBorder(null);
        jPanel3.add(txtCnfPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 310, 20));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 160));

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel2.setText("Participant id :-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 108, -1));

        lblParticipantid.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        lblParticipantid.setText("jLabel3");
        jPanel1.add(lblParticipantid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 92, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel4.setText("Name :-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 300, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel5.setText("Phone no :-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 92, -1));

        txtPhone.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtPhone.setBorder(null);
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel6.setText("Email :-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtMail2.setBackground(new java.awt.Color(173, 192, 234));
        txtMail2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtMail2.setBorder(null);
        jPanel1.add(txtMail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 950, 10));

        jLabel40.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel40.setText("Skills -");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, -1));

        txtSkill9.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtSkill9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, 30));

        txtSkill10.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtSkill10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 160, 30));

        txtSkill11.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill11.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtSkill11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 160, 30));

        txtSkill12.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtSkill12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtSkill12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 160, 30));

        jLabel41.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel41.setText("Qualification :-");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, -1));

        txtQualification2.setBackground(new java.awt.Color(173, 192, 234));
        txtQualification2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtQualification2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtQualification2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 760, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 950, -1));

        btnBack.setBackground(new java.awt.Color(173, 192, 234));
        btnBack.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        btnDownloadResume.setBackground(new java.awt.Color(173, 192, 234));
        btnDownloadResume.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDownloadResume.setText("Download Resume");
        btnDownloadResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadResumeActionPerformed(evt);
            }
        });
        jPanel1.add(btnDownloadResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new/viewAllQualified.png"))); // NOI18N
        jLabel42.setText("jLabel42");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 184, 250, 180));

        btnSendMail.setBackground(new java.awt.Color(173, 192, 234));
        btnSendMail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSendMail.setText("Send Mail");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });
        jPanel1.add(btnSendMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBrowseFileActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnBrowseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFile1ActionPerformed
        // TODO add your handling code here:
     
       
    }//GEN-LAST:event_btnBrowseFile1ActionPerformed

    private void btnCreateAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccount1ActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_btnCreateAccount1ActionPerformed

    private void btnDownloadResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadResumeActionPerformed
        // TODO add your handling code here:
      File file;
        JFileChooser chooser=new JFileChooser();
        
        chooser.setDialogTitle("Choose Directory for downlaod");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int result =chooser.showDialog(null,"Choose");
        
        if (result == chooser.APPROVE_OPTION) 
        {   
            file=chooser.getSelectedFile();
            try
            {
                Blob b=ParticipantsDAO.getParticipantsResume(participantid);
                byte []arr=b.getBytes(1,(int)b.length());
                FileOutputStream output=new FileOutputStream(file.toString()+"/"+txtName.getText()+".pdf");
                output.write(arr);
                
                JOptionPane.showMessageDialog(null,"File Downloaded and saved SuccessFully !!!","Success",JOptionPane.INFORMATION_MESSAGE);
                
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            catch(FileNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null,"File not found","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            catch(IOException ex)
            {
                JOptionPane.showMessageDialog(null,"IO error","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            
        } 
        else if (result == chooser.CANCEL_OPTION) 
        {
            System.out.println("Cancel was selected");
        }  
    }//GEN-LAST:event_btnDownloadResumeActionPerformed

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
         ResultsPojo result=new ResultsPojo();
         result.setpId(participantid);
         result.setJobId(CurrentUser.getId());
         result.setPercentage(-1.0);
         result.setSelectedByHr("Yes");
         final String username="mrabhig2000@gmail.com";
        final String password="vhgeafzwgyqelzoq";
        //step 1
        Properties prop = new Properties();
	prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        
        MyAuthenticator myAuth=new  MyAuthenticator(username,password);
        Session session=Session.getInstance(prop, myAuth);
        
        try{
            boolean responce=ResultDAO.participantSelected(result);
            String pt=HrDAO.getCompanyNameById(CurrentUser.getId());
            Message message=new MimeMessage(session);
            InternetAddress[]recipients=InternetAddress.parse("aadarshjain1805@gmail.com ");
            message.setRecipients(Message.RecipientType.TO, recipients);
            message.setSubject("Written Test Result Of "+pt);
            message.setText("Dear Student,\n" +
                                             "\n" +
                                            "  \n" +
                                             "\n" +
                            "Congratulations!! \n" +
                            "\n" +
                            " \n" +
                            "\n" +
                            "You have qualified the Technical test.\n" +
                            "\n" +
                            "And we will contact you for the Technical Interview shortly.\n" +
                            "\n" +
                            " \n" +
                            "\n" +
                            " \n" +
                            "\n" +
                            "Regards,\n" +
                            "\n" +
                            CurrentUser.getName());
            Transport.send(message);
            System.out.println("Mail successfully send");
        }
        catch (MessagingException e) {
            e.printStackTrace();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSendMailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new HrViewAllParticipantsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new HrViewParticipantFrame().setVisible(true);
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowseFile;
    private javax.swing.JButton btnBrowseFile1;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnCreateAccount1;
    private javax.swing.JButton btnDownloadResume;
    private javax.swing.JButton btnSendMail;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblParticipantid;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblPid1;
    private javax.swing.JPasswordField txtCnfPwd;
    private javax.swing.JPasswordField txtCnfPwd1;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtFilePath1;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMail1;
    private javax.swing.JTextField txtMail2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JPasswordField txtPwd1;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtQualification1;
    private javax.swing.JTextField txtQualification2;
    private javax.swing.JTextField txtSkill1;
    private javax.swing.JTextField txtSkill10;
    private javax.swing.JTextField txtSkill11;
    private javax.swing.JTextField txtSkill12;
    private javax.swing.JTextField txtSkill2;
    private javax.swing.JTextField txtSkill3;
    private javax.swing.JTextField txtSkill4;
    private javax.swing.JTextField txtSkill5;
    private javax.swing.JTextField txtSkill6;
    private javax.swing.JTextField txtSkill7;
    private javax.swing.JTextField txtSkill8;
    private javax.swing.JTextField txtSkill9;
    // End of variables declaration//GEN-END:variables
}
